package `in`.opening.area.zustapp.home

enum class ACTION {
    OPEN_USER_BOOKING, OPEN_LOCATION, SEARCH_PRODUCT, SEARCH_NON_VEG,
    ORDER_DETAIL, SUGGEST_PRODUCT, ORDER_WA, OPEN_PROFILE, NAV_BACK, LANGUAGE_DIALOG, PHONE_CALL, GROCERY_TAB, NON_VEG_TAB
}
